#!/bin/bash

# Get the full path to this script
scriptPath=$(dirname $(readlink -f $0))
bashDir=$scriptPath/bash
emacsDir=$scriptPath/emacs
gitDir=$scriptPath/git

# bash
bashFiles=`ls $bashDir`
for i in $bashFiles; do
   cat >> $HOME/.bashrc <<EOF
# Stieg config...

if [ -r $bashDir/$i ]; then
   . $bashDir/$i
fi

EOF
done

# Git goodies
gitFiles=`ls $gitDir`
for i in $gitFiles; do
    ln -svi $gitDir/$i "$HOME/.$i"
done

# Emacs
destEmacsDir="$HOME/.emacs.d"
mkdir -p $destEmacsDir
ln -svi $emacsDir/init.el "${destEmacsDir}/init.el"
ln -svi $emacsDir/plugins "${destEmacsDir}/plugins"