#!/bin/bash
set -x
set -e

# Get the full path to this script
SCRIPT_DIRNAME=$"$(dirname "$(readlink -f "$0")")"

# Shells RC files should all source .stiegrc
ln -fsv $SCRIPT_DIRNAME/.stiegrc $HOME/.stiegrc
for f in $HOME/.{bashrc,zshrc}; do
    grep -q .stiegrc $f && continue
    cat >> $f <<EOF
# Stieg's config
. \$HOME/.stiegrc
EOF
done

# Link the other hidden files.
for d in $SCRIPT_DIRNAME/{emacs,git,screen}; do
    for f in $(ls $d); do
	     test -L "$HOME/.$f" || ln -svi $d/$f "$HOME/.$f"
    done
done
