#!/bin/bash

# Useful Apt Aliases
if which apt-get >/dev/null; then
    alias agis='sudo -i apt-get install'
    alias agud='sudo -i apt-get update'
fi

if which apt-cache >/dev/null; then
    alias acs='apt-cache search'
fi