#!/bin/bash
# Find way to get location of this file
# Absolute path to this script. /home/user/bin/foo.sh
#SCRIPT=$(readlink -f $0)
# Absolute path this script is in. /home/user/bin
#SCRIPTPATH=`dirname $SCRIPT`
#echo $SCRIPT

# This assumes you have a put a symlink to bash-init in your home directory
# Modify this as you see fit.
this_dir=~/.bash-init


# Useful Aliases
. $this_dir/aliases