#!/bin/bash
#
# How these Aliases work...
#
# These aliases are created by breaking up the command into
# its syllables and then concatinating the first leter of
# every syllable into the aliased command.
#
# So in example
#   apt-get update translates to agud.
#
# Of course this won't work for every command and there will
# be commands that will share the same alias.  Whe that happens
# I try to work around it by appending the next letter after the
# last syllable until I don't have a conflict.  I am always looking
# for a better way to do it, so if you have one, drop me a line.
#
# -stieg
#

# Useful Apt Aliases
if which apt-get &>/dev/null; then
    alias   agis='sudo -i apt-get install'
    alias   agud='sudo -i apt-get update'
    alias agatrm='sudo -i apt-get autoremove'
    alias   agug='sudo -i apt-get upgrade'
    alias  agdug='sudo -i apt-get dist-upgrade'
    alias   agrm='sudo -i apt-get remove'
fi

if which apt-cache &>/dev/null; then
    alias  acse='apt-cache search'
    alias  acsh='apt-cache show'
    alias  acdp='apt-cache depends'
    alias   aca='apt-cache add'
    alias  acsp='apt-cache showpkg'
fi

# Useful Yum Aliases
if which yum &>/dev/null; then
    alias yis='sudo yum install'
    alias yer='sudo yum erase'
    alias yl='yum list'
    alias yif='yum info'
fi

# Perforce
if which p4 &>/dev/null; then
    alias p4ds='p4 describe'
    alias p4op='p4 opened'
    alias p4sm='p4 submit'
    alias  p4s='p4 sync'
    alias p4ed='p4 edit'
    alias p4rv='p4 revert'
    alias  p4c='p4 change'
    alias p4ce='p4 client'
fi

# Editor
alias   edt='emacs -nw'
#alias    ls='ls --color=auto'
alias    ll='ls -lgF'
alias    la='ls -A'
alias     l='ls -CF'
alias  grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Add an aliases to resource the init
alias sourceInit='. ~/.bashrc'
# alias sin='sourceInit'

# Footprint alias for seeing sizes quickly.
alias fp='du --max-depth=0'

# SSH Aliases for Katsu
alias katsugw='ssh -fTN katsu.triplehelix.org'
alias ras-katsu='ssh -t katsu.triplehelix.org screen -Rd'

# local
alias ras-lucifer='ssh -t lucifer'

# Useful Aliases for Size
alias space='du --si --max-depth=1'

# Mac Aliases
alias ll='ls -l'
